config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/representative_login',  to: 'sessions#representative_new'
  post '/representative_login', to: 'sessions#representative_create'
  get '/sender_login', to: 'sample_login#sender_login'
  get '/receiver_login', to: 'sample_login#receiver_login'
  get '/functions', to: 'static_pages#functions'

  scope module: 'admin' do
    get '/tag_suggest', to: 'articles#tag_suggest'
    resources :representatives, only: [:new, :create, :show, :destroy] do
      get '/admin_signup', to: 'representatives#new_admin_user' 
      get '/event', to: 'representatives#event'
      resources :destroy_accounts,   only: [:new, :create, :edit, :destroy]
      resources :articles do
        resources :images, only: :destroy
        resources :incompletes, only: [:index, :update, :destroy]
        delete 'all_incompletes', to: 'incompletes#all_destroy'
      end
      resources :users, expect: :show do
        get '/complete', to: 'users#complete'
        get '/add_admin', to: 'users#add_admin'
        get '/delete_admin', to: 'users#delete_admin'
      end
    end
  end

  namespace :staff do
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :representatives, only: :show do
      get '/event', to: 'representatives#event'
      resources :articles do
        resources :incompletes, only: [:update, :destroy]
      end
      resources :members, except: [:show, :edit]
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/article.rb
class Article < ApplicationRecord
  self.inheritance_column = :_type_disabled
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 50 }
  validates :type, presence: true
  validate :check_plan_days
  enum type: { information: 0, plans: 1 }
  DATE_DEFINE_TODAY = 2
  DEADLINE_DAYS = 2

  belongs_to :user
  belongs_to :representative
  belongs_to :member, optional: true
  has_many   :incompletes, dependent: :destroy
  has_many   :incompleted_list, -> { incompleted_list }, foreign_key: 'article_id',
                                                         class_name: 'Incomplete'
  has_many   :completed_list,   -> { completed_list },   foreign_key: 'article_id',
                                                         class_name: 'Incomplete'
  scope :includes_user_incompletes, -> { includes(:user, :incompletes) }
  scope :plans,             -> { where(type: 1) }
  scope :information,       -> { where(type: 0) }
  scope :emergencies,       -> { where(emergency: true) }
  scope :sender_articles,   -> { joins(:user).merge(User.sender_users) }
  scope :of_senders,        -> { where(users: { sender: 'sender' }) }
  scope :child_tags,        -> (main_tag) { where('parent_tag = ?', main_tag) }
  scope :search_child_tags, -> (keyword) { where('child_tag LIKE ?', "#{keyword}%") }
  scope :search,            -> (word) {
                              where('UPPER(title) LIKE ? OR UPPER(content) LIKE ?',
                                    "%#{word.upcase}%", "%#{word.upcase}%")
                            }
  scope :not_short_plans,   -> { where('plan_days > ?', DATE_DEFINE_TODAY) }
  scope :today_plans,       -> {
                              where('start_date <= ? AND end_date >= ?', Date.today, Date.today).
                                or(where('start_date = ?', Date.today))
                            }
  scope :plans_nearing_deadline, -> { where('end_date <= ?', Date.today.next_day(DEADLINE_DAYS)) }
  scope :plans_nearing_start,    -> {
                                   where('start_date <= ?', Date.today.next_day(DEADLINE_DAYS)).
                                     where('start_date >= ?', Date.today)
                                 }
  scope :incompleted_list,  -> { joins(:incompletes).merge(Incomplete.incompleted_list) }
  scope :child_tags_asc,    -> { order(child_tag: :asc) }

  def self.article_order(order)
    return order("articles.created_at DESC") unless order

    if order == 'start_date ASC'
      where('start_date >= ?', Date.today).order('start_date ASC')
    elsif order == 'end_date ASC'
      where('end_date >= ?', Date.today).order('start_date ASC')
    else
      order(order)
    end
  end

  def validate_tag
    if parent_tag.blank? && child_tag.present?
      false
    else
      true
    end
  end

  def plan_days_value
    (end_date - start_date).to_i
  end

  def check_plan_days
    if start_date && end_date && start_date > end_date
      errors.add(:end_date, "は、開始日以降の日付を設定して下さい。")
    end
  end

  # ユーザーが作業を完了してるか確認
  def completed_as(user)
    incompletes.find_by(user_id: user.id).completed?
  end

  # 自身が予定であることを確認し、それが完了していたらtrueを返す
  def complete_plan?
    return false unless type == 'plans'
    plan_incomp = incompletes.first
    plan_incomp.present? && plan_incomp.completed?
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::Base
  protect_from_forgery except: :image_destroy
  skip_before_action :logged_in_user, :sender_only, only: [:tag_suggest]
  before_action :correct_article_or_admin, only: [:edit, :update, :destroy]
  TITLE_LENGTH_MAXIMUM = 50

  layout 'admin_sidebar'

  def index
    includes_plans = current_representative.plans.includes_user_incompletes
    art_plans = includes_plans.sender_articles.page(params[:page])
    art_information = current_representative.information.page(params[:page]).includes_user_incompletes
    keyword = params[:keyword]
    search_type = params[:type]
    if keyword.present?
      if search_type == '連絡情報'
        @articles = art_information.search(keyword).article_order(params[:order])
      else
        @articles = art_plans.search(keyword).article_order(params[:order])
      end
    else
      if search_type == 'スタッフの予定'
        @articles = art_plans.article_order(params[:order])
      else
        @articles = art_information.article_order(params[:order])
      end
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_representative.articles.build
  end

  def create
    @article = @representative.articles.build(article_params)
    if @article.end_date && @article.start_date
      @article.plan_days = @article.plan_days_value
    end

    if @article.validate_tag && @article.save
      # incomplete保存の分岐
      if @article.type == 'plans'
        incomplete = @article.incompletes.build(user_id: current_user.id)
        flash[:danger] = 'エラーが発生し作業管理チェック機能が追加されませんでした。' unless incomplete.save
      elsif @article.type == 'information' && params[:article][:complete_function] == "1"
        save_incompletes(@article)
      end
      flash[:success] = "#{@article.title}を登録しました。"
      redirect_to [current_representative, @article]
    else
      render 'new'
    end
  end

  def edit
    @article = @article.decorate
  end

  def update
    if @article.update_attributes(article_params)
      # incomplete保存の分岐
      if @article.type == 'plans'
        # 既に同じincompleteがある場合はその場で処理終了
        return redirect_to [current_representative, @article] if @article.incompletes.find_by(user_id: current_user.id)
        incomplete = @article.incompletes.build(user_id: current_user.id)
        flash[:danger] = 'エラーが発生し作業管理チェック機能が追加されませんでした。' unless incomplete.save
      elsif @article.type == 'information' && params[:article][:complete_function] == "1"
        save_incompletes(@article) if @article.incompletes.empty?
      end
      flash[:success] = "記事(タイトル: #{@article.title.abridgement_strings(TITLE_LENGTH_MAXIMUM)})を更新しました。"
      redirect_to [current_representative, @article]
    else
      render 'edit'
    end
  end

  def destroy
    title = @article.title
    @article.destroy
    flash[:warning] = "記事(タイトル: #{title.abridgement_strings(TITLE_LENGTH_MAXIMUM)})を削除しました。"
    redirect_to representative_articles_path(current_representative)
  end

  def tag_suggest
    @tags = current_representative.articles.
      child_tags(params[:main_tag]).
      search_child_tags(params[:keyword]).
      child_tags_asc.
      distinct.pluck(:child_tag)
    render json: @tags
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :emergency, :type, :start_date, :end_date,
                                    :user_id, :representative_id, :parent_tag, :child_tag, :complete_function, images: [])
  end

  def correct_article_or_admin
    @article = Article.find(params[:id])
    unless correct_model_or_admin?(@article.user)
      flash[:danger] = 'アクセス権限がありません。'
      redirect_to @article.representative
    end
  end

  def save_incompletes(article)
    Incomplete.transaction do
      @representative.receivers.each do |receiver|
        incomplete = article.incompletes.build(user_id: receiver.id)
        incomplete.save!
      end
    end
  rescue
    flash[:danger] = 'エラーが発生し作業管理チェック機能が追加されませんでした。'
  end
end

app/controllers/staff/articles_controller.rb
class Staff::ArticlesController < Staff::Base
  before_action :correct_article_or_admin, only: [:edit, :update, :destroy]
  before_action :sender_only, only: :create, if: :information_article
  TITLE_LENGTH_MAXIMUM = 50

  layout 'staff_sidebar'

  def index
    art_plans = current_user.plans.page(params[:page]).includes_user_incompletes
    art_information = current_representative.information.page(params[:page]).includes_user_incompletes
    keyword = params[:keyword]
    search_type = params[:type]

    if keyword.present?
      if search_type == '連絡情報'
        @articles = art_information.search(keyword).article_order(params[:order])
      else
        @articles = art_plans.search(keyword).article_order(params[:order])
      end
    else
      if search_type == 'スタッフの予定'
        @articles = art_plans.article_order(params[:order])
      elsif search_type == '未完了'
        @articles = current_user.articles.incompleted_list.page(params[:page]).includes_user_incompletes
      else
        @articles = art_information.article_order(params[:order])
      end
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_representative.articles.build
    get_members
  end

  def create
    @article = @representative.articles.build(article_params)
    if @article.end_date && @article.start_date
      @article.plan_days = @article.plan_days_value
    end
    if @article.type == 'plans' && @article.save
      flash[:success] = "#{@article.title}を登録しました。"
      incomplete = @article.incompletes.build(user_id: current_user.id)
      flash[:danger] = 'エラーが発生し作業管理チェック機能が追加されませんでした。' unless incomplete.save
      redirect_to [:staff, current_representative, @article]
    else
      get_members
      render 'new'
    end
  end

  def edit
    @article = @article.decorate
    get_members
  end

  def update
    if params[:article][:complete_function] == '1' && @article.update_attributes(article_params)
      unless @article.user.incompletes.plan_incomplete(@article)
        @article.incompletes.build(user_id: current_user.id)
      end
      flash[:success] = "記事(タイトル: #{@article.title.abridgement_strings(TITLE_LENGTH_MAXIMUM)})を更新しました。"
      redirect_to [:staff, current_representative, @article]
    else
      get_members
      render 'edit'
    end
  end

  def destroy
    title = @article.title
    @article.destroy
    flash[:warning] = "「#{title.abridgement_strings(TITLE_LENGTH_MAXIMUM)}」を削除しました。"
    redirect_to staff_representative_articles_path(current_representative)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :emergency, :type, :start_date, :end_date,
                                    :user_id, :representative_id, :member_id, :complete_function, images: [])
  end

  def correct_article_or_admin
    @article = Article.find(params[:id])
    unless correct_model_or_admin?(@article.user)
      flash[:danger] = 'アクセス権限がありません。'
      redirect_to [:staff, @article.representative]
    end
  end

  def get_members
    @members = [[current_user.name, ""]]
    current_user.members.map do |member|
      @members << [member.name, member.id]
    end
  end

  # 受け取ったarticleがinformationの時trueを返す
  def information_article
    if @article
      @article.type == 'information'
    else
      params[:article][:type] == 'information'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<li class="article-container article-<%= article.type %>" id="article-<%= article.id %>">
  <%= link_to [current_representative, article] do %>
    <div class='article-header_container d-flex justify-content-between'>
      <p>
        <% if article.emergency? %>
          <span class='article-header_emergency'>緊急</span>
        <% end %>
        <%= article.title.abridgement_strings(80) %>
      </p>
      <div class='article-date_wrapper d-flex'>
      <% if article.start_date %>
        <p class='article-date_content'><span>開始日・終了日</span>：<%= article.start_date %> ~ <%= article.end_date %></p>
      <% end %>
        <p class='article_type'><%= article.type_i18n%></p>
      </div>
    </div>
    <div class='article-content_container'>
      <%= article.content.abridgement_strings(300) %>
    </div>
  <% end %>
  <div class='article-footer_container d-flex justify-content-between'>
    <a class="user_modal-link" data-toggle="modal" data-target="#userModal"><%= article.user.name %></a>
    <% if article.complete_function? %>
      <div class='article_complete-wrapper d-flex'>
        <p class='article_complete-rabel'>作業状態</p>
        <div id='article_completed-icon'>
          <%= article.decorate.article_completed_icon %>
        </div>
        <div id='article_complete-button'>
          <%= article.decorate.completed_button %>
        </div>
      </div>
    <% end %>
    <p>投稿日:<%= article.created_at.strftime('%Y/%m/%d') %></p>
  </div>
</li>
<%= render 'shared/user_modal', user: article.user %>

app/views/admin/articles/_form.html.erb
<div class='form-wrapper' id='article-form-wrapper'>
  <div class='form-intermediate' id='article-form-intermediate'>
    <%= form_with model: [current_representative, article], local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <div class='article-form_top form-border form-row'>
        <div class="form-group col-md-7">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group col-md-4 d-flex align-items-end">
          <p class='sm-letter text-right'><%= current_user.name %>の</p>
          <%= f.select :type, Article.types.keys.map{|k| [I18n.t("enums.article.type.#{k}"), k]}, {}, class: 'form-control' %>
        </div>
      </div>
      <div class='article-form_date form-border-dashed form-inline'>
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class:'form-control' %>
        <%= f.label :end_date %>
        <%= f.date_field :end_date, class:'form-control' %>
        <div class='form-check ml-5 ml-sm-2'>
          <%= f.check_box :emergency, class: 'form-check-input' %>
          <%= f.label :emergency, class: 'article-header_emergency form-check-label' %>
        </div>
      </div>
      <div class='article-form_main form-border-dashed orm-group'>
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="article-form_file form-border form-group">  
        <%= f.label :images, '添付ファイル' %>
        <% if article.images.present? %>
          <% article.images.each do |image| %>
            <li><%= image.filename %><%= link_to '削除', image.decorate.image_destroy_path(article), { method: :delete, params: { image_id: image.id }} %></li>
          <% end %>
        <% end %>
        <%= f.file_field :images, multiple: true, class:'form-control-file' %>
      </div>
      <div class="form-row form-border article_tag-form">
        <div class='form-group'>
          <%= f.label :parent_tag %>
          <%= f.text_field :parent_tag, class:'form-control parent_tag-form' %>
        </div>
        <div class='form-group'>
          <%= f.label :child_tag %>
          <%= f.text_field :child_tag, class:'form-control child_tag-form', autocomplete: 'off', disabled: true %>
        </div>
      </div>
      <% if article.complete_function? %>
        <% if article.type == 'plans' %>
          <p>※予定の登録ではタグ登録は行なえません。</p>
        <% else %>
          <%= article.all_destroy_link %>
        <% end %>
      <% else %>
        <div class='complete_check-form form-inline' id='complete_check-wrapper'>
          <%= f.check_box :complete_function, class: 'form-check-input' %>
          <%= f.label :complete_function, '作業の完了を確認できるようにする' %>
          <p>この項目にチェックをすると、発信された作業内容を完了させた受信側のユーザーを確認することが出来ます。</p>
        </div>
      <% end %>
      <div class='btn-wrapper'>
        <%= f.submit yield(:button_text), class:'btn btn-lg btn-outline-primary'%>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<% provide(:title, "情報･予定編集") %>
<% provide(:button_text, '更新') %>

<div class='article-edit_container'>
  <div class='page-title-wrapper'>
    <h1 class='default-page-title'>情報･予定編集</h1>
  </div>
  <%= render 'form', article: @article %>
  <div class='article-show_buttons'>
    <%= link_to '詳細', representative_article_path(@article.representative), class: 'bottom-links_right bottom-links' %>
    <% if correct_model_or_admin?(@article.user) %>
      <%= link_to '削除', [@article.representative, @article], method: :delete,
                                                                data: { confirm:  "投稿を削除します。よろしいですか？" },
                                                                class: 'bottom-links_right bottom-links' %>
    <% end %>
  </div>
</div>

app/views/admin/articles/index.html.erb
<% provide(:title, '連絡情報・予定一覧') %>

<div class='articles-container index-container'>
  <div class='container'>
    <div class='page-title-wrapper'>
      <h1 class='default-page-title'>連絡情報・予定一覧</h1>
    </div>
    <div class='articles_other-link index-header_links'>
      <%= link_to '連絡情報・予定の登録を行う', new_representative_article_path(current_representative), class: 'navbar-brand' %>
    </div>
    <div class='navbar-collapse d-lg-flex articles_header index-header'>
      <div class='articles_header-top d-flex index-header_top'>
        <%= contents_link_item('連絡情報', representative_articles_path(current_representative, type: '連絡情報'),
                               '連絡情報') %>
        <%= contents_link_item('スタッフの予定', representative_articles_path(current_representative, type: 'スタッフの予定'),
                               'スタッフの予定') %>
        <%= form_with url: representative_articles_path(current_representative), method: :get, id: 'order-submit', local: true do |f| %>
          <%= f.hidden_field :type, value: params[:type] %>
          <%= f.hidden_field :keyword, value: params[:keyword] %>
          <%= f.select :order, {'投稿日 降順':'articles.created_at DESC', '投稿日 昇順':'articles.created_at ASC',
                                '終了日時が近い順':'end_date ASC', '開始日時が近い順':'start_date ASC' },
                                {selected: params[:order]}, {class: 'form-control article-order'} %>
        <% end %>
      </div>
      <div class='articles_header-bottom index-header_bottom'>
        <ul class='navbar-nav'>
          <li class='form-inline'>
            <%= form_with url: representative_articles_path(current_representative), method: :get, local: true do |f| %>
              <%= f.text_field :keyword, placeholder: 'キーワードで検索',class: 'form-control' %><%= f.select :type, ['連絡情報', 'スタッフの予定'], {selected: params[:type]}, class: 'form-control' %>
              <%= f.submit '検索', name: nil, class:'btn btn-outline-dark' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <%= indicate_keyword('articles') %>
    <% if @articles.any? %>
      <ol id='articles-partial'>
        <%= render @articles %>
      </ol>
    <% else %>
      <h2>連絡情報・予定はありません。</h2>
    <% end %>
    <%= paginate @articles %>
    <div class='custom-hidden-field'>
      <p class='hidden-field-type'></p>
    </div>
  </div>
</div>

app/views/admin/articles/index.js.erb
<% if @articles.any? %>
  $('#articles-partial').html('<%= j(render @articles ) %>')
<% else %>
  $('#articles-partial').html('<h2>連絡情報・予定はありません。</h2>')
<% end %>

app/views/admin/articles/new.html.erb
<% provide(:title, "情報･予定新規登録") %>
<% provide(:button_text, '登録') %>

<div class='container artile-new_container'>
  <div class='page-title-wrapper'>
    <h1 class='default-page-title'>情報･予定新規登録</h1>
  </div>
  <%= render 'form', article: @article %>
</div>

app/views/admin/articles/show.html.erb
<% provide(:title, '情報詳細') %>

<div class='article-show' id="article-<%= @article.id %>">
  <div class='page-title-wrapper'>
    <h1 class='default-page-title'>連絡情報・予定詳細</h1>
  </div>
  <% if @article.start_date || @article.end_date %>
    <div class='article-show_date'>
      <p>
        開始日<span class='article_start-date'><%= @article.start_date %></span>
        終了日<span class='article_end-date'><%= @article.end_date %></span>
      </p>
    </div>
  <% end %>
  <div class="article-show_container article-show_<%= @article.type == "plans" ? + 'plans' : + 'info' %>">
    <div class='article-show_title d-flex justify-content-between'>
      <p>
        <% if @article.emergency? %><span class='article-header_emergency'>緊急</span><% end %>
        <%= @article.title %>
      </p>
      <a class="user_modal-link user-name" data-toggle="modal" data-target="#userModal"><%= @article.user.name %></a>
    </div>
    <div class='article-show_content'>
      <p class='article-show_content-top'><%= @article.content %></p>
      <% if @article.parent_tag.present? %>
        <p class='article-show_content-tag'>メインタグ: <%= @article.parent_tag %><span>サブタグ: <%= @article.child_tag %></span></p>
      <% end %>
    </div>
    <div class='article-show_footer'>
    <% if @article.images.attached? %>
      <div class='article-show_downloads'>
        <ul>
        <% @article.images.each do |image| %>
          <li><div class="download icon"></div><span><%= link_to image.filename, rails_blob_path(image), download: "ダウンロード" %></span></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <div class='d-flex'>
        <p class='article-created-at'>投稿日時:<%= @article.created_at.strftime('%Y/%m/%d') %></p>
        <% if @article.complete_function? %>
          <div class='article_complete-wrapper d-flex'>
            <p class='article_complete-rabel'>作業状態</p>
            <div id='article_completed-icon'>
              <%= @article.decorate.article_completed_icon %>
            </div>
            <div id='article_complete-button'>
              <%= @article.decorate.completed_button %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class='article-show_buttons'>
    <%= link_to '一覧へ戻る', representative_articles_path(@article.representative), class: 'bottom-links_left bottom-links' %>
    <% if correct_model_or_admin?(@article.user) %>
      <%= link_to '編集', edit_representative_article_path(@article.representative), class: 'bottom-links_center bottom-links' %>
      <%= link_to '削除', [@article.representative, @article], method: :delete,
                                                               data: { confirm:  "投稿を削除します。よろしいですか？" },
                                                               class: 'bottom-links_right bottom-links' %>
    <% end %>
  </div>
</div>
<%= render 'shared/user_modal', user: @article.user %>
<script>
  history.replaceState(null, document.getElementsByTagName('title')[0].innerHTML, null);
  window.addEventListener('popstate', function(e) {
    window.location.reload();
  });
</script>