config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/representative_login',  to: 'sessions#representative_new'
  post '/representative_login', to: 'sessions#representative_create'
  get '/sender_login', to: 'sample_login#sender_login'
  get '/receiver_login', to: 'sample_login#receiver_login'
  get '/functions', to: 'static_pages#functions'

  scope module: 'admin' do
    get '/tag_suggest', to: 'articles#tag_suggest'
    resources :representatives, only: [:new, :create, :show, :destroy] do
      get '/admin_signup', to: 'representatives#new_admin_user' 
      get '/event', to: 'representatives#event'
      resources :destroy_accounts,   only: [:new, :create, :edit, :destroy]
      resources :articles do
        resources :images, only: :destroy
        resources :incompletes, only: [:index, :update, :destroy]
        delete 'all_incompletes', to: 'incompletes#all_destroy'
      end
      resources :users, expect: :show do
        get '/complete', to: 'users#complete'
        get '/add_admin', to: 'users#add_admin'
        get '/delete_admin', to: 'users#delete_admin'
      end
    end
  end

  namespace :staff do
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :representatives, only: :show do
      get '/event', to: 'representatives#event'
      resources :articles do
        resources :incompletes, only: [:update, :destroy]
      end
      resources :members, except: [:show, :edit]
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/shared/_article_complete.html.erb
<% if request.path.include?('staff') %>
  <%= form_with model: [:staff, current_representative, article, incomplete], method: :patch do |f| %>
    <%= f.hidden_field :completed, value: true %>
    <%= f.submit '完了済にする', class: "btn btn-sm btn-outline-success" %>
  <% end %>
<% else %>
  <%= form_with model: [current_representative, article, incomplete], method: :patch do |f| %>
    <%= f.hidden_field :completed, value: true %>
    <%= f.submit '完了済にする', class: "btn btn-sm btn-outline-success" %>
  <% end %>
<% end %>

app/views/shared/_article_incomplete.html.erb
<% if request.path.include?('staff') %>
  <%= form_with model: [:staff, current_representative, article, incomplete], method: :delete do |f| %>
    <%= f.hidden_field :completed, value: true %>
    <%= f.submit '未完了に戻す', class: "btn btn-sm btn-outline-secondary" %>
  <% end %>
<% else %>
  <%= form_with model: [current_representative, article, incomplete], method: :delete do |f| %>
    <%= f.hidden_field :completed, value: true %>
    <%= f.submit '未完了に戻す', class: "btn btn-sm btn-outline-secondary" %>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class='container'>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= object.errors.count %>個のエラーが発生しました。
      </div>
      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class='form-wrapper'>
  <div class='form-intermediate'>
    <%= form_with model: [representative, user], local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <% if logged_in? %>
        <div class='form-group user-type_form'>
          ユーザータイプ: <%= f.select :sender, User.senders.keys.map {|k| [I18n.t("enums.user.sender.#{k}"), k]} %>
        </div>
      <% else %>
        <%= f.hidden_field :sender, value: 'sender' %>
      <% end %>
      <div class='form-group'>
        <%= f.label :name, class:'required-item' %>
        <%= f.text_field :name, class:'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :email, class: 'required-email' %>
        <%= f.text_field :email, class:'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :context %>
        <%= f.text_field :context, class:'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :phone_number %>
        <p class='form_note'>ハイフン無し</p>
        <%= f.text_field :phone_number, class:'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :staff_id, class:'required-item' %>
        <p class='form_note'>半角英数最低8文字</p>
        <%= f.text_field :staff_id, class:'form-control staff_id-form' %>
      </div>

      <div class='form-group'>
        <%= f.label :password, class:'required-item' %>
        <p class='form_note'>
          ・半角英数最低6文字以上<br>
          ・英数字をそれぞれ最低一つ以上<br>
          ・大文字小文字区別
        </p>
        <%= f.password_field :password, class:'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :password_confirmation, class:'required-item' %>
        <%= f.password_field :password_confirmation, class:'form-control' %>
      </div>

      <div class='form-group form-inline'>
        <%= f.check_box :terms_check, class: 'form-control' %>
        <span><button type="button" class="terms-button" data-toggle="modal" data-target="#exampleModalLong">利用規約</button>に同意する</span>
      </div>

      <div class='submit-btn'>
        <%= f.submit yield(:button_text), class:'btn btn-lg btn-primary'%>
      </div>
    <% end %>
  </div>
  <div class='form-intermediate form-intermediate-sub'>
      <p>管理者ユーザー登録が出来ていない方はこちら <%= link_to '管理者ユーザー登録', representative_admin_signup_path(@representative), class: 'animsition-link', data: {"turbolinks"=>false} %></p>
  </div>
</div>
<%= render 'shared/terms' %>

app/views/shared/_receiver_side_menu.html.erb
<div class='sidebar-container'>
  <div class='sidebar-wrapper'>
    <div class='sidebar-main'>
      <ul>
        <%= sidebar_link_item('ホーム', staff_representative_path(current_representative), data: {"turbolinks"=>false}) %>
        <%= sidebar_link_item('連絡情報･予定一覧', staff_representative_articles_path(current_representative)) %>
        <%= sidebar_link_item('予定の登録', new_staff_representative_article_path(current_representative)) %>
        <%= sidebar_link_item('メンバー一覧', staff_representative_members_path(current_representative)) %>
        <%= sidebar_link_item('メンバー登録', new_staff_representative_member_path(current_representative), admin_user: false, class: 'animsition-link') %>
      </ul>
    </div>
    <div class='sidebar-sub'>
      <ul>
        <li><button type="button" class="terms-button" data-toggle="modal" data-target="#exampleModalLong">利用規約</button></li>
      </ul>
    </div>
  </div>
</div>
<%= render 'shared/terms' %>

app/views/shared/_sender_side_menu.html.erb
<div class='sidebar-container'>
  <div class='sidebar-wrapper'>
    <div class='sidebar-main'>
      <ul>
        <%= sidebar_link_item('ホーム', current_representative, data: {"turbolinks"=>false}) %>
        <%= sidebar_link_item('連絡情報･予定一覧', representative_articles_path(current_representative)) %>
        <%= sidebar_link_item('連絡情報･予定の登録', new_representative_article_path(current_representative)) %>
        <%= sidebar_link_item('ユーザー一覧', representative_users_path(current_representative)) %>
        <%= sidebar_link_item('ユーザー登録', new_representative_user_path(current_representative), class: 'animsition-link', admin_user: false) %>
      </ul>
    </div>
    <div class='sidebar-sub'>
      <ul>
        <li><button type="button" class="terms-button" data-toggle="modal" data-target="#exampleModalLong">利用規約</button></li>
        <li><%= link_to '退会(全データ削除)', new_representative_destroy_account_path(current_representative), class: 'animsition-link' %></li>
      </ul>
    </div>
  </div>
</div>
<%= render 'shared/terms' %>

app/views/shared/_terms.html.erb
<div class="modal terms_container fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">利用規約</h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>この利用規約（以下，「本規約」といいます。）は，appleHANA（以下，「当人」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

        <h2>第1条（適用）</h2>
        <p>本規約は，ユーザーと当人との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>
        <p>当人は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</p>
        <p>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</p>
        <h2>第2条（利用登録）</h2>
        <p>本サービスにおいては，登録希望者が本規約に同意の上，当人の定める方法によって利用登録を申請し，当人がこれを承認することによって，利用登録が完了するものとします。</p>
        <p>当人は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</p>
        <p>利用登録の申請に際して虚偽の事項を届け出た場合</p>
        <p>本規約に違反したことがある者からの申請である場合</p>
        <p>その他，当人が利用登録を相当でないと判断した場合</p>
        <h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
        <p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</p>
        <p>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当人は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</p>
        <p>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当人に故意又は重大な過失がある場合を除き，当人は一切の責任を負わないものとします。</p>
        <h1>プライバシーポリシー</h1>
        <h2>第1条（個人情報）</h2>
        <p>「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>
        <h2>第2条（個人情報の収集方法）</h2>
        <p>当人は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当人の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</p>
        <h2>第3条（個人情報を収集・利用する目的）</h2>
        <p>当人が個人情報を収集・利用する目的は，以下のとおりです。
          <ul>
            <li>当人サービスの提供・運営のため</li>
            <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
            <li>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
            <li>利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</li>
            <li>ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</li>
            <li>上記の利用目的に付随する目的</li>
          </ul>
        </p>
        <h2>第4条（利用目的の変更）</h2>
        <p>当人は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。</p>
        <p>利用目的の変更を行った場合には，変更後の目的について，当人所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</p>
        <h2>第5条（個人情報の第三者提供）</h2>
        <p>当人は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</p>
        <ul>
          <li>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
          <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
          <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
          <li>予め次の事項を告知あるいは公表し，かつ当人が個人情報保護委員会に届出をしたとき</li>
          <ul>
            <li>利用目的に第三者への提供を含むこと</li>
            <li>第三者に提供されるデータの項目</li>
            <li>第三者への提供の手段または方法</li>
            <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
            <li>本人の求めを受け付ける方法</li>
          </ul>
        </ul>
        <p>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。</p>
        <ul>
          <li>当人が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
          <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
          <li>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
        </ul>
        <h2>第6条（個人情報の開示）</h2>
        <p>当人は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。</p>
        <ul>
          <li>本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</li>
          <li>当人の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
          <li>その他法令に違反することとなる場合</li>
        </ul>
        <p>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。</p>
        <h2>第7条（個人情報の訂正および削除）</h2>
        <p>ユーザーは，当人の保有する自己の個人情報が誤った情報である場合には，当人が定める手続きにより，当人に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。</p>
        <p>当人は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。</p>
        <p>当人は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</p>
        <h2>第8条（個人情報の利用停止等）</h2>
        <p>当人は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</p>
        <p>前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。</p>
        <p>当人は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。</p>
        <p>前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</p>
        <h2>第9条（プライバシーポリシーの変更）</h2>
        <p>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</p>
        <p>当人が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</p>
        <h2>第10条（お問い合わせ窓口）</h2>
        <p>本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。</p>
        <br>
        <p>担当者:sampleHANA</p>
        <p>Eメールアドレス：applenin88@yahoo.co.jp</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_modal.html.erb
<div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered ">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"><%= user.name %></h4>
            </div>
            <div class="modal-body"> 
                <h5>部署・所属</h5>
                <p><%= user.context %></p>
                <h5>メールアドレス</h5>
                <p><%= mail_to user.email %></p>
                <h5>電話番号</h5>
                <p><%= user.phone_number %></p>
                <% if current_user.sender? %>
                  <h5>ユーザー属性</h5>
                  <p><%= user.sender_i18n %><%= tag.span '管理者', class: 'user-modal_admin' if user.admin? %></p>
                  <h5>ユーザー登録日</h5>
                  <p><%= user.created_at.strftime('%Y/%m/%d') %></p>
                <% end %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">閉じる</button>
            </div>
        </div>
    </div>
</div>