config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/representative_login',  to: 'sessions#representative_new'
  post '/representative_login', to: 'sessions#representative_create'
  get '/sender_login', to: 'sample_login#sender_login'
  get '/receiver_login', to: 'sample_login#receiver_login'
  get '/functions', to: 'static_pages#functions'

  scope module: 'admin' do
    get '/tag_suggest', to: 'articles#tag_suggest'
    resources :representatives, only: [:new, :create, :show, :destroy] do
      get '/admin_signup', to: 'representatives#new_admin_user' 
      get '/event', to: 'representatives#event'
      resources :destroy_accounts,   only: [:new, :create, :edit, :destroy]
      resources :articles do
        resources :images, only: :destroy
        resources :incompletes, only: [:index, :update, :destroy]
        delete 'all_incompletes', to: 'incompletes#all_destroy'
      end
      resources :users, expect: :show do
        get '/complete', to: 'users#complete'
        get '/add_admin', to: 'users#add_admin'
        get '/delete_admin', to: 'users#delete_admin'
      end
    end
  end

  namespace :staff do
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :representatives, only: :show do
      get '/event', to: 'representatives#event'
      resources :articles do
        resources :incompletes, only: [:update, :destroy]
      end
      resources :members, except: [:show, :edit]
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  include Token
  attr_accessor :remember_token, :reset_token

  has_secure_password
  before_save :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  VALID_ID_REGEX = /\A(?=.*?[a-z])(?=.*?\d)\w+\z/.freeze # 英数字をそれぞれ1文字以上は必ず入れる。大文字を区別する
  VALID_PHONE_REGEX = /\A\d+\z/.freeze

  validates :name,         presence: true,
                           length: { maximum: 50 }
  validates :email,        presence: { if: :sender_user },
                           length: { maximum: 255 },
                           format: { with: VALID_EMAIL_REGEX, allow_blank: true },
                           uniqueness: { case_sensitive: false }
  validates :staff_id,     presence: true,
                           length: { minimum: 6, maximum: 100 },
                           format: { with: VALID_ID_REGEX },
                           uniqueness: true
  validates :password,     presence: true,
                           length: { minimum: 8 },
                           allow_nil: true
  validates :phone_number, length: { minimum: 10, maximum: 11 },
                           format: { with: VALID_PHONE_REGEX },
                           allow_blank: true
  enum sender: { sender: true, receiver: false }

  has_many :articles,    dependent: :destroy
  has_many :members,     dependent: :destroy
  has_many :incompletes, dependent: :destroy
  has_many :plans, -> { plans }, foreign_key: 'user_id',
                                 class_name: 'Article'
  belongs_to :representative

  scope :admin_users,  -> { where(admin: true) }
  scope :sender_users, -> { where(sender: 1) }
  scope :receivers,    -> { where(sender: 0) }
  scope :search,       -> (word) { where('name LIKE ? OR context LIKE ?', "%#{word}%", "%#{word}%") }

  # remember_digestにハッシュ化されたトークンを入れる
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def self.users_order(order)
    order ? order(order) : order('created_at DESC')
  end

  private

  def downcase_email
    self.email = email.downcase if email.present?
  end

  def sender_user
    sender == 'sender'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  skip_before_action :logged_in_user,   only: [:new, :create]
  skip_before_action :sender_only,      only: [:new, :create, :update]
  before_action :logged_in_correct_rep, only: [:new, :create]
  before_action :correct_user,          only: [:edit, :update, :destroy]
  before_action :correct_user_or_admin, only: [:destroy]
  before_action :current_user_admin,    only: [:add_admin, :delete_admin]

  def index
    current_senders = current_representative.sender_users.page(params[:page])
    current_receivers = current_representative.receivers.page(params[:page])
    keyword = params[:keyword]
    search_sender = params[:sender]
    if keyword.present?
      if search_sender == '情報発信メンバー'
        @users = current_senders.search(keyword).users_order(params[:order])
      else
        @users = current_receivers.search(keyword).users_order(params[:order])
      end
    else
      if search_sender == '情報受信メンバー'
        @users = current_receivers.users_order(params[:order])
      else
        @users = current_senders.users_order(params[:order])
      end
    end
    render layout: 'admin_sidebar'
  end

  def new
    @user = @representative.users.build
    @admin_user = false
  end

  def create
    @user = @representative.users.build(user_params)
    if params[:user][:terms_check] == "0"
      flash.now[:alert] = '利用規約の確認をして下さい。'
      render 'new'
      return
    end
    if request.referer&.include?("/admin_signup")
      @user.admin = true
      @user.sender = true
    end
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました。'
      # representative#showから登録した場合completeビューへ、ホームから登録した場合はnewビューへリダイレクト
      if logged_in?
        redirect_to representative_user_complete_path(@representative, @user)
      else
        log_in(@user)
        redirect_to representative_path(@representative)
      end
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    render layout: 'admin_sidebar'
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:city_id].present?
      city = City.find_by(weather_id: params[:user][:city_id])
      city ? @user.update(city: city.name, city_id: city.weather_id) : flash[:danger] = '都市の設定に失敗しました。'
      if current_user.sender?
        redirect_to(@representative) && return
      else
        redirect_to(staff_representative_path(@representative)) && return
      end
    else
      return redirect_to staff_representative_path(@representative) unless current_user.sender?
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を更新しました'
        redirect_to representative_users_path(@representative)
      else
        render 'edit'
      end
    end
  end

  def destroy
    name = @user.name
    @user.destroy
    flash[:warning] = "ユーザー:#{name}を削除しました。"
    redirect_to representative_users_path
  end

  def complete
    @user = User.find(params[:user_id])
  end

  def add_admin
    user = User.find(params[:user_id])
    user.admin = true
    if user.save
      flash[:success] = "ユーザー: #{user.name}に管理者権限を付与しました。"
      redirect_to representative_users_path(@representative)
    else
      flash[:danger] = '管理者権限の付与に失敗しました。'
      redirect_to representative_users_path(@representative)
    end
  end

  def delete_admin
    user = User.find(params[:user_id])
    user.admin = false
    if user.save
      flash[:success] = "ユーザー: #{user.name}に管理者権限を削除しました。"
      redirect_to representative_users_path(@representative)
    else
      flash[:danger] = '管理者権限の削除に失敗しました。'
      redirect_to representative_users_path(@representative)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :sender, :email, :context, :phone_number, :staff_id,
                                 :password, :password_confirmation, :city, :city_id)
  end

  def correct_user
    @user = User.find(params[:id])
    if @user.sender? && !current_user?(@user)
      flash[:danger] = 'アクセス権限がありません。'
      redirect_to current_representative
    end
  end

  def correct_user_or_admin
    @user = User.find(params[:id])
    if @user.sender? && !current_user?(@user) || !current_user.admin?
      flash[:danger] = 'アクセス権限がありません。'
      redirect_to current_representative
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # ログインユーザーがadminのみリンク表示
  def button_to_change_admin(user)
    if user.admin?
      link_to '管理者権限を削除', representative_user_delete_admin_path(user.representative, user),
              data: { confirm: "ユーザー: #{user.name}に管理者権限を削除します。\n本当によろしいですか？" },
              class: 'admin-deprivation_authority'
    else
      if user.sender?
        link_to '管理者権限を付与', representative_user_add_admin_path(user.representative, user),
                data: { confirm: "ユーザー: #{user.name}に管理者権限を付与します
                                 (必要なユーザーのみに管理者権限を与えるよう注意して下さい)\n
                                 本当によろしいですか？" },
                class: 'admin-grant_authority'
      end
    end
  end

  # 対象のユーザーがsenderの場合は本人のみ、receiverの場合はログインユーザーがsenderの場合のみリンク表示
  def button_to_delete_user(user)
    if (user.sender? && current_user?(user) || current_user.admin?) || (!user.sender? && current_user.sender?)
      link_to 'ユーザーを削除', representative_user_path(current_representative, user),
              method: :delete,
              data: { confirm: "ユーザー: #{user.name}を削除します。\n本当によろしいですか？" },
              class: 'user-delete_button'
    end
  end
end

app/views/admin/users/_user.html.erb
<li class="user-container d-lg-flex justify-content-between user-<%= user.sender %>" id="user-<%= user.id %>">
  <div class="user-wrapper">
    <div class='user-header_container d-lg-flex'>
      <p class='user-header_name user-name'><%= user.name %></p>
      <p class='user-header_sender'>
        <%= user.sender_i18n %>
      </p>
      <p class='user-header_context'><span>部門・部署</span><span><%= user.context %></span></p>
      <% if user.admin? %>
        <p class='user-header_admin'>管理者</p>
      <%end%>
    </div>
    <div class='user-footer_container d-lg-flex justify-content-between'>
      <p><%= mail_to user.email %></p>
      <p class='user-footer_created'><span>作成日時</span><span><%= user.created_at.strftime('%Y/%m/%d') %></span></p>
    </div>
  </div>
  <% if current_user.admin? %>
    <div class='user_admin-buttons d-lg-flex flex-column'>
      <%= button_to_change_admin(user) %>
      <%= button_to_delete_user(user) %>
    </div>
  <% end %>
</li>

app/views/admin/users/complete.html.erb
<% provide(:title, "ユーザー登録完了") %>

<div class='row'>
  <div class='col-xs-12 col-md-6 offset-md-3 complete-table'>
    <table class='table'>
      <tr><td class='table-td-name'>名前</td><td class='table-td-content'><%= @user.name %></td></tr>
      <tr><td class='table-td-name'>メンバータイプ</td><td class='table-td-content'><%= @user.sender_i18n %></td></tr>
      <tr><td class='table-td-name'>メールアドレス</td><td class='table-td-content'><%= @user.email %></td></tr>
      <tr><td class='table-td-name'>部署・所属名</td><td class='table-td-content'><%= @user.context %></td></tr>
      <tr><td class='table-td-name'>電話番号</td><td class='table-td-content'><%= @user.phone_number %></td></tr>
      <tr><td class='table-td-name'>ユーザーID</td><td class='table-td-content'><%= @user.staff_id %></td></tr>
    </table>
  </div>
  <div class='container complete-links text-center'>
    <%= link_to 'ユーザー一覧', representative_users_path(current_representative), class:'bottom-links_left bottom-links' %>
    <%= link_to '編集する', edit_representative_user_path(current_representative, @user), class:'bottom-links_center bottom-links' %>
    <%= link_to '次のユーザーを登録する', new_representative_user_path(current_representative), admin_user: false, class:'bottom-links_right bottom-links animsition-link' %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>
<% provide(:button_text, "更新") %>

<div class='container'>
  <div class='row justify-content-between'>
    <div class="col-md-10 offset-md-1">
      <div class='container user-form_container'>
        <div class='page-title-wrapper'>
          <h1 class='default-page-title'><%= @user.name %>　ユーザー編集</h1>
        </div>
        <p class='danger-note'>*印は必須入力です。</p>
        <%= render 'shared/form', user: @user, representative: @representative, admin_user: false %>
        <%= link_to 'このユーザーを削除する', representative_user_path(current_representative, @user), method: :delete,
                                      data: { confirm: "ユーザー: #{@user.name}を削除します。この作業は取り消せません。
                                                        \n本当によろしいですか？" },
                                      class: 'delete-link_button' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>

<div class='users-container index-container'>
  <div class='container'>
    <div class='page-title-wrapper'>
      <h1 class='default-page-title'>ユーザー一覧</h1>
    </div>
    <div class='users_other-link index-header_links'>
      <%= link_to 'ユーザー登録を行う', new_representative_user_path(current_representative), class: 'navbar-brand' %>
    </div>
    <div class='navbar-collapse d-lg-flex users_header index-header'>
      <div class='users_header-top d-flex index-header_top'>
        <%= contents_link_item('情報発信ユーザー', representative_users_path(current_representative, sender: '情報発信メンバー'),
                               '情報発信メンバー') %>
        <%= contents_link_item('情報受信ユーザー', representative_users_path(current_representative, sender: '情報受信メンバー'),
                               '情報受信メンバー') %>
        <%= form_with url: representative_users_path(current_representative), method: :get, id: 'order-submit', local: true do |f| %>
          <%= f.hidden_field :sender, value: params[:sender] %>
          <%= f.hidden_field :keyword, value: params[:keyword] %>
          <%= f.select :order, { '登録日 降順':'created_at DESC', '登録日 昇順':'created_at ASC',
                                 '名前 降順':'name ASC', '名前 昇順':'name DESC' },
                               {selected: params[:order]}, {class: 'form-control user-order'} %>
        <% end %>
      </div>
      <div class='users_header-bottom index-header_bottom'>
        <ul class='navbar-nav'>
          <li class='form-inline'>
            <%= form_with url: representative_users_path(current_representative), method: :get, local: true do |f| %>
              <%= f.text_field :keyword, class: 'form-control' %><%= f.select :sender, ['情報発信メンバー', '情報受信メンバー'], {}, class: 'form-control' %>
              <%= f.submit '検索', name: nil, class:'btn btn-outline-dark' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <%= indicate_keyword('users') %>
    <% if @users.any? %>
      <ol id='users-partial'>
        <%= render @users %>
      </ol>
    <% else %>
      <h2>ユーザーが見つかりません。</h2>
    <% end %>
    <%= paginate @users %>
    <div class='custom-hidden-field'>
      <p class='hidden-field-type'></p>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<% provide(:button_text, "登録") %>

<div class='container'>
  <div class='row justify-content-between'>
    <div class="col-md-8 offset-md-2">
      <div class='container user-form_container'>
        <h1 class='default-page-title'><%= @representative.name %>　ユーザー登録</h1>
        <p class='danger-note'>*印は必須入力です。</p>
        <%= render 'shared/form', user: @user, representative: @representative, admin_user: @admin_user %>
        <p class='admin-new-note'>まだ管理者ユーザーを登録していない方は<%= link_to 'こちら', representative_admin_signup_path(@representative), class: 'animsition-link', data: {"turbolinks"=>false} %></p>
      </div>
    </div>
  </div>
</div>